### ISSUE TITLE
Not "Pfingstmontag" today

### ISSUE THREAD

**Issue by alexander-zimmermann** [MariusLang/node-red-contrib-feiertage-germany#16]
Hey folks,

any idea why my installation means it is not Pfingstmontag today? Timezone is correct.

BR
Alex

<img width="316" alt="Bildschirmfoto 2022-06-06 um 18 42 47" src="https://user-images.githubusercontent.com/4419315/172207021-df4317e0-7858-4a0b-a44a-0ac2098f235d.png">
<img width="356" alt="Bildschirmfoto 2022-06-06 um 18 43 05" src="https://user-images.githubusercontent.com/4419315/172207067-a9e6d60d-b5ee-46d1-9155-a777c8e578a6.png">

**Comment by MariusLang** [comment]
Dear Alex,
thanks for using node-red-contrib-feiertage 🥳

The issue you mentioned is caused by a bug in the code.
Don't worry, it isn't caused by a wrong timezone configuration on your system.

The upcoming version of node-red-contrib-feiertage will fix this issue.
The fix is going to be released tomorrow.

Best regards Marius

**Comment by MariusLang** [comment]
Dear Alex,

the new version 1.4.3 fixes the issue you mentioned.
You can easily upgrade the node in NodeRed to **node-red-contrib-feiertage-germany@1.4.3**

Thanks for reporting this issue 👍

Best Regards Marius
